### ISSUE TITLE
请教一个问题关node切换目录的问题

### ISSUE THREAD

**Issue by chengchongzhen** [biaov/create-mine#5]
我看到您这边的代码, 执行了再某个工作目录下执行 install 功能， 我这边遇到了下载完成后执行 cd xxx 命令不生效的问题，不知道您这边有没有遇到？

这是您仓库的代码
```
  const { stdout } = await exec(install, {
        cwd: processCwd
      })
```

这是我的
```js
 loading.succeed('创建模版成功!') // 成功loading
        if (fs.existsSync(dest)) {
          process.chdir(dest)
          console.info(`cd ${ name }`)
          console.info('npm i')
          console.info('npm start\n')
        }
```

**Comment by biaov** [comment]
有完整代码demo吗

**Comment by chengchongzhen** [comment]
![image](https://github.com/biaov/create-mine/assets/52627267/a28cc52c-e60f-4423-95f2-2e6243b72ebe)

https://github.com/chengchongzhen/mini-cli/blob/main/bin/cli.js

**Comment by chengchongzhen** [comment]
因为不生效我把那个切换目录的代码删了

**Comment by biaov** [comment]
切换目录的代码是什么样的？

**Comment by chengchongzhen** [comment]
execSync(`cd ${projectName} `)

**Comment by biaov** [comment]
- 这是因为 `exec` 只会触发子进程，无法影响到父进程或其他子进程，所以你想直接改变父进程的工作目录暂未发现实现方法
- 如果你想在某个特定目录下执行命令，你可以设置 `cwd` 配置项

**Comment by chengchongzhen** [comment]
谢谢
